## Class exercises - simple configuration for a single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../hello-world/hello.md"
        title: "Hello!"
      - file: "../hello-world/world.md"
        title: "World!"

## Class exercises - configuration for multiple classes
# ---
# classes:
#   # `class_id` may be omitted if there is only one class
#   # in this configuration file
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../hello-world/hello.md"
#         title: "Hello!"
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../hello-world/world.md"
#         title: "World!"

## Class exercises - configuration for different supported syntaxes
# ---
# classes:
#   - exercises:
#       - file: "../markup-syntaxes/markdown.md"
#         # `syntax` is optional
#         # can be "md" | "md-extended" | "rst"
#         # uses file extension as fallback
#         syntax: "md"
#         title: "Markdown!"
#       - file: "../markup-syntaxes/markdown-extended.md"
#         syntax: "md-extended"
#         title: "Extended markdown"
#       - file: "../markup-syntaxes/restructured.rst"
#         syntax: "rst"
#         title: "Restructed"
#       - file: "../relative-images/md-with-relative-imgs.md"
#         title: "Relative images"

## Class exercises - configuration for different exercise types
# ---
# classes:
#   - exercises:
#       - file: "../markup-syntaxes/markdown.md"
#         # `exercise_type` is optional
#         # can be "lesson" | "lab_challenge"
#         # defaults to "lesson"
#         exercise_type: "lab_challenge"
#         title: "Lab challenge"
#         scripts:
#           - file: "../scripts/challenge.sh"
#             lab_resource_index: 0
