# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../hello-world/hello.md"
        title: "Hello!"
      - file: "../hello-world/world.md"
        title: "World!"
      - file: "../relative-images/md-with-relative-imgs.md"
        title: "Relative images"
      - file: "../markup-syntaxes/markdown-codelabs-flavor.md"
        title: "Codelabs flavor"

# Class exercises - configuration for multiple classes
# ---
# classes:
#   # `class_id` may be omitted if there is only one class in this file
#   - class_id: "<your_class_id>"
#     exercises:
#       # `file` is relative to .strigo directory
#       - file: "../hello-world/hello.md"
#         title: "Hello!"
#       - file: "../hello-world/world.md"
#         title: "World!"
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../markup-syntaxes/markdown.md"
#         title: "Markdown!"
#         # `syntax` is optional
#         # can be "md" | "rst"
#         # uses file extension as fallback
#         syntax: "md"
#       - file: "../markup-syntaxes/restructured.rst"
#         title: "Restructed"
#         syntax: "rst"
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../relative-images/md-with-relative-imgs.md"
#         title: "Relative images"
