# Classes exercises configuration
---
classes:
  # `class_id` may be omitted if there is only one class in this file
  - class_id: "6036b5ca919a21bf0455eccd"
    exercises:
      # `file` is relative to .strigo directory
      - file: "../hello-world/hello.md"
        title: "Hello!"
      - file: "../hello-world/world.md"
        title: "World!"
  - class_id: "M6n3yjBhg9SXhTFjH"
    exercises:
      # `syntax` is optional
      # can be "md" | "rst" | "adoc"
      # uses file extension as fallback
      - file: "../markup-syntaxes/markdown.md"
        syntax: "md"
        title: "Markdown!"
      - file: "../markup-syntaxes/restructured.rst"
        syntax: "rst"
        title: "Restructed"
      - file: "../markup-syntaxes/asciidoc.adoc"
        syntax: "adoc"
        title: "ASCII doc"
  - class_id: "603b9df00f809ae626af3117"
    exercises:
      - file: "../relative-images/md-with-relative-imgs.md"
        title: "Relative images"
