# Classes exercises configuration
---
classes:
  - class_id: M6n3yjBhg9SXhTFjH
    exercises:
      # `file` can be relative or absolute
      - file: "../hello-world/hello.md"
      - file: "../hello-world/world.md"
